# Generated by Django 6.0.2 on 2026-02-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='Lecturer', max_length=50),
            preserve_default=False,
        ),
    ]
