# Generated by Django 6.0.2 on 2026-02-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teacher_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='Lecturer', max_length=50),
        ),
    ]
