# Generated by Django 6.0.2 on 2026-02-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_teacher_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
    ]
